// <auto-generated />
using System;
using DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DeliverySystemDb))]
    [Migration("20220729112940_FakeDataandDatabaseComplited")]
    partial class FakeDataandDatabaseComplited
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GetDelivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "deliveryenter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "deliveryhandover"
                        },
                        new
                        {
                            Id = 4,
                            Name = "deliverytake"
                        },
                        new
                        {
                            Id = 5,
                            Name = "getorder"
                        },
                        new
                        {
                            Id = 6,
                            Name = "addproduct"
                        },
                        new
                        {
                            Id = 7,
                            Name = "addorder"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "acompany@gmail.com",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bcompany@gmail.com",
                            Password = "345"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperationClaimId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OperationClaimId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            OperationClaimId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            OperationClaimId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            OperationClaimId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            OperationClaimId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            OperationClaimId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            OperationClaimId = 7,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"), 1L, 1);

                    b.Property<string>("CargoMan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            DeliveryId = 1,
                            CargoMan = "Ahmet",
                            DeliveryDate = new DateTime(2022, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            VehicleNumber = "02A223"
                        },
                        new
                        {
                            DeliveryId = 2,
                            CargoMan = "Mehmet",
                            DeliveryDate = new DateTime(2022, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            VehicleNumber = "20B2020"
                        },
                        new
                        {
                            DeliveryId = 3,
                            CargoMan = "Ali",
                            DeliveryDate = new DateTime(2021, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            VehicleNumber = "30C234"
                        },
                        new
                        {
                            DeliveryId = 4,
                            CargoMan = "Esra",
                            DeliveryDate = new DateTime(2021, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            VehicleNumber = "15v3030"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ContactNumber = "",
                            EndPoint = "Zonguldak",
                            OrderDate = new DateTime(2021, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            StartPoint = "Bursa"
                        },
                        new
                        {
                            OrderId = 2,
                            ContactNumber = "",
                            EndPoint = "Samsun",
                            OrderDate = new DateTime(2021, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            StartPoint = "İstanbul"
                        },
                        new
                        {
                            OrderId = 3,
                            ContactNumber = "",
                            EndPoint = "İstanbul",
                            OrderDate = new DateTime(2021, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            StartPoint = "İzmir"
                        },
                        new
                        {
                            OrderId = 4,
                            ContactNumber = "",
                            EndPoint = "Antalya",
                            OrderDate = new DateTime(2021, 7, 29, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            StartPoint = "Muğla"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Tablet"
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Telefon"
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "Hoparlör"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
